# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Interest'},
        ),
        migrations.AlterModelOptions(
            name='rgs_user',
            options={'verbose_name': 'RGS User'},
        ),
    ]
